# Generated by Django 3.2.9 on 2021-11-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPRemoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfpusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='cfpusers',
            name='UName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
